global_frame: odom
static_map: false
rolling_window: true
track_unknown_space: false
width: 10 #20
height: 10 #20
origin_x: 0.0
origin_y: 0.0

plugins:
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}