planners:
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: DWAPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller_frequency: 4.0
controller_patience: 5.0
controller_max_retries: 3

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

planner_max_retries: 1  # To enable recovery behavior, set to positive value.
recovery_patience: 30.0