//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Nmea
{
    [Serializable]
    public class GpgsvMsg : Message
    {
        public const string k_RosMessageName = "nmea_msgs/Gpgsv";
        public override string RosMessageName => k_RosMessageName;

        //  Total number of satellites in view and data about satellites
        //  Because the NMEA sentence is limited to 4 satellites per message, several
        //  of these messages may need to be synthesized to get data about all visible
        //  satellites.
        public HeaderMsg header;
        public string message_id;
        //  Number of messages in this sequence
        public byte n_msgs;
        //  This messages number in its sequence. The first message is number 1.
        public byte msg_number;
        //  Number of satellites currently visible
        public byte n_satellites;
        //  Up to 4 satellites are described in each message
        public GpgsvSatelliteMsg[] satellites;

        public GpgsvMsg()
        {
            this.header = new HeaderMsg();
            this.message_id = "";
            this.n_msgs = 0;
            this.msg_number = 0;
            this.n_satellites = 0;
            this.satellites = new GpgsvSatelliteMsg[0];
        }

        public GpgsvMsg(HeaderMsg header, string message_id, byte n_msgs, byte msg_number, byte n_satellites, GpgsvSatelliteMsg[] satellites)
        {
            this.header = header;
            this.message_id = message_id;
            this.n_msgs = n_msgs;
            this.msg_number = msg_number;
            this.n_satellites = n_satellites;
            this.satellites = satellites;
        }

        public static GpgsvMsg Deserialize(MessageDeserializer deserializer) => new GpgsvMsg(deserializer);

        private GpgsvMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.message_id);
            deserializer.Read(out this.n_msgs);
            deserializer.Read(out this.msg_number);
            deserializer.Read(out this.n_satellites);
            deserializer.Read(out this.satellites, GpgsvSatelliteMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.message_id);
            serializer.Write(this.n_msgs);
            serializer.Write(this.msg_number);
            serializer.Write(this.n_satellites);
            serializer.WriteLength(this.satellites);
            serializer.Write(this.satellites);
        }

        public override string ToString()
        {
            return "GpgsvMsg: " +
            "\nheader: " + header.ToString() +
            "\nmessage_id: " + message_id.ToString() +
            "\nn_msgs: " + n_msgs.ToString() +
            "\nmsg_number: " + msg_number.ToString() +
            "\nn_satellites: " + n_satellites.ToString() +
            "\nsatellites: " + System.String.Join(", ", satellites.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
