//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Nmea
{
    [Serializable]
    public class GprmcMsg : Message
    {
        public const string k_RosMessageName = "nmea_msgs/Gprmc";
        public override string RosMessageName => k_RosMessageName;

        //  Message from GPRMC NMEA String
        public HeaderMsg header;
        public string message_id;
        public double utc_seconds;
        public string position_status;
        public double lat;
        public double lon;
        public string lat_dir;
        public string lon_dir;
        public float speed;
        public float track;
        public string date;
        public float mag_var;
        public string mag_var_direction;
        public string mode_indicator;

        public GprmcMsg()
        {
            this.header = new HeaderMsg();
            this.message_id = "";
            this.utc_seconds = 0.0;
            this.position_status = "";
            this.lat = 0.0;
            this.lon = 0.0;
            this.lat_dir = "";
            this.lon_dir = "";
            this.speed = 0.0f;
            this.track = 0.0f;
            this.date = "";
            this.mag_var = 0.0f;
            this.mag_var_direction = "";
            this.mode_indicator = "";
        }

        public GprmcMsg(HeaderMsg header, string message_id, double utc_seconds, string position_status, double lat, double lon, string lat_dir, string lon_dir, float speed, float track, string date, float mag_var, string mag_var_direction, string mode_indicator)
        {
            this.header = header;
            this.message_id = message_id;
            this.utc_seconds = utc_seconds;
            this.position_status = position_status;
            this.lat = lat;
            this.lon = lon;
            this.lat_dir = lat_dir;
            this.lon_dir = lon_dir;
            this.speed = speed;
            this.track = track;
            this.date = date;
            this.mag_var = mag_var;
            this.mag_var_direction = mag_var_direction;
            this.mode_indicator = mode_indicator;
        }

        public static GprmcMsg Deserialize(MessageDeserializer deserializer) => new GprmcMsg(deserializer);

        private GprmcMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.message_id);
            deserializer.Read(out this.utc_seconds);
            deserializer.Read(out this.position_status);
            deserializer.Read(out this.lat);
            deserializer.Read(out this.lon);
            deserializer.Read(out this.lat_dir);
            deserializer.Read(out this.lon_dir);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.track);
            deserializer.Read(out this.date);
            deserializer.Read(out this.mag_var);
            deserializer.Read(out this.mag_var_direction);
            deserializer.Read(out this.mode_indicator);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.message_id);
            serializer.Write(this.utc_seconds);
            serializer.Write(this.position_status);
            serializer.Write(this.lat);
            serializer.Write(this.lon);
            serializer.Write(this.lat_dir);
            serializer.Write(this.lon_dir);
            serializer.Write(this.speed);
            serializer.Write(this.track);
            serializer.Write(this.date);
            serializer.Write(this.mag_var);
            serializer.Write(this.mag_var_direction);
            serializer.Write(this.mode_indicator);
        }

        public override string ToString()
        {
            return "GprmcMsg: " +
            "\nheader: " + header.ToString() +
            "\nmessage_id: " + message_id.ToString() +
            "\nutc_seconds: " + utc_seconds.ToString() +
            "\nposition_status: " + position_status.ToString() +
            "\nlat: " + lat.ToString() +
            "\nlon: " + lon.ToString() +
            "\nlat_dir: " + lat_dir.ToString() +
            "\nlon_dir: " + lon_dir.ToString() +
            "\nspeed: " + speed.ToString() +
            "\ntrack: " + track.ToString() +
            "\ndate: " + date.ToString() +
            "\nmag_var: " + mag_var.ToString() +
            "\nmag_var_direction: " + mag_var_direction.ToString() +
            "\nmode_indicator: " + mode_indicator.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
